//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessStep
    {
        public int ProcessId { get; set; }
        public int StepId { get; set; }
        public bool Mandatory { get; set; }
        public string Params { get; set; }
    
        public virtual Process Process { get; set; }
        public virtual Step Step { get; set; }
    }
}
