//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public Process()
        {
            this.ProcessSteps = new HashSet<ProcessStep>();
            this.Reasons = new HashSet<Reason>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int CallType { get; set; }
        public int CallerType { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ICollection<ProcessStep> ProcessSteps { get; set; }
        public virtual ICollection<Reason> Reasons { get; set; }
    }
}
